// AUTO-GENERATED by scripts/fetch_calendar_events.py — do not edit by hand.
// Synced from the club's public Google Calendar; merged with the
// hard-coded EVENTS in site-data.js by js/site.js (hard-coded wins).
export const CALENDAR_EVENTS = [
  {"title": "Pena Lab Project Meeting 10 [Room PDB A204]", "date": "2026-04-13T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 9 [Room PDB A204]", "date": "2026-04-06T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 8 [Room PDB A204]", "date": "2026-03-30T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 7 [Room PDB A204]", "date": "2026-03-23T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 6 [Room PDB A204]", "date": "2026-03-09T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 5 [Room PDB A204]", "date": "2026-03-02T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 4 [Room PDB A204]", "date": "2026-02-23T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 3 [Room PDB A204]", "date": "2026-02-16T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 2 [Room PDB A204]", "date": "2026-02-09T18:00", "location": "Psychology Department Building, Psychology Dept Bldg, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Pena Lab Project Meeting 1 [Room PDB A204]", "date": "2026-02-04T18:00", "location": "Psychology Department Building, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "[CNS] - Projects Start Window", "date": "2026-02-02T18:00", "location": "TBA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "End of Semester GBM / Project Presentations", "date": "2025-11-20T18:00", "location": "Time TBD Location TBD", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Social/Fundraiser", "date": "2025-10-24T18:00", "location": "Time TBD - Location TBD", "blurb": "", "image": "images/placeholder.png"},
  {"title": "ML/AI 4 NeuroSci", "date": "2025-10-20T18:00", "location": "TBD", "blurb": "Collaboration with ThinkAI", "image": "images/placeholder.png"},
  {"title": "Python Basics for Neuro/DataSci Workshop: Part 2", "date": "2025-09-18T18:00", "location": "TBD", "blurb": "Collab event with Codeducation", "image": "images/placeholder.png"},
  {"title": "Python Basics for Neuro/DataSci Workshop: Part 1", "date": "2025-09-16T18:00", "location": "TBD", "blurb": "Collab event with Codeducation", "image": "images/placeholder.png"},
  {"title": "Projects Meeting", "date": "2025-09-16T18:00", "location": "TBA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "CNS Projects Start", "date": "2025-09-08T18:00", "location": "TBA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "GBM #1 + Intro to Comp Neuro / Room PDB A204", "date": "2025-09-04T18:00", "location": "Psychology Department Building, 1107 W Call St, Tallahassee, FL 32304, USA", "blurb": "", "image": "images/placeholder.png"},
  {"title": "Tally Biotech Expo", "date": "2025-07-19T10:00", "location": "Challenger Learning Center of Tallahassee, 200 S Duval St, Tallahassee, FL 32301, USA", "blurb": "", "image": "images/placeholder.png"}
];
