// ============================================================================
//  CompNeuroSociety - SITE CONTENT (the only file you need to edit!)
// ============================================================================
//  HOW TO UPDATE:
//  • EVENTS: add new events to the TOP of the list. Date format
//    "YYYY-MM-DDTHH:MM" (24h local). The home page + events page update
//    themselves: next 2 upcoming + latest past on home, full timeline on
//    events.html, countdowns included. Put photos in images/ first.
//    NOTE: events also auto-sync from the club's public Google Calendar
//    (js/calendar-events.js, regenerated by scripts/fetch_calendar_events.py
//    via a GitHub Action every 6h). Events listed here always win over a
//    calendar entry on the same day with a similar title — so use this list
//    for curated blurbs/photos, and the calendar for everything else. To give
//    a calendar event a photo, put e.g. "#img:gbm" in its description
//    (keys are defined in scripts/fetch_calendar_events.py).
//  • PEOPLE: edit LEADERSHIP / GRAD_COUNCIL / MENTORS / TEAM (people.html).
//  • PROJECTS: CURRENT_PROJECT (set to `null` when there's no active team,
//    the page shows a "forming soon" placeholder) + PAST_PROJECTS
//    (projects.html); APPLICATIONS.open flips the apply button on/off.
//  • LINKS: every form/social URL, used across pages.
// ============================================================================

export const LINKS = {
  joinForm: "https://docs.google.com/forms/d/e/1FAIpQLSeqCh_WXl_rf-VN8YQPkutY8kIcHM4SX1K7l_qnbl7gqzzCAA/viewform",
  teamForm: "https://docs.google.com/forms/d/e/1FAIpQLSfd-vkrRiNgYRNY7rwi8tR3r-pd48KYgRtGMRNDFoUBXBLprQ/viewform",
  projectForm: "https://docs.google.com/forms/d/e/1FAIpQLScRBfy8KiEscIm7tHRrBUQkJ1IZqItF0BFHA04Gez7lOR_j0w/viewform",
  mentorForm: "https://docs.google.com/forms/d/e/1FAIpQLSemPSmSWOTgw2W4bqnN6N7dHp5ah236jmIFHwJ-VauATRxm6Q/viewform",
  leadEventForm: "https://docs.google.com/forms/d/e/1FAIpQLSfA6zFAnmT1cDZghn1a9XTLhUvKN5pWfXS3K3inVgz028DkCQ/viewform",
  contactForm: "https://docs.google.com/forms/d/e/1FAIpQLScl6mZQyUl-RaMnC2vbm66aq9_yOaN-d0mZLhUlyMYOliZvEw/viewform",
  instagram: "https://www.instagram.com/compneurosocietyfsu/",
  linkedin: "https://linkedin.com/company/compneurosociety-at-fsu",
  discord: "https://discord.gg/k6fXKr6JTU",
  hq: "https://hq.fsu.edu/compneurosociety",
  calendar: "https://calendar.google.com/calendar/embed?src=compneurosociety%40gmail.com&ctz=America%2FNew_York",
  email: "compneurosociety@outlook.com",
  constitution: "constitution.pdf",
  chaptersPage: "chapters.html",
};

// --- EVENTS (newest first). The two "example" entries are placeholders -
// --- replace them with real events and delete the `example: true` line.
export const EVENTS = [
  { title: "Fall Involvement Fair", date: "2026-08-27T17:00", location: "Tucker Civic Center",
    blurb: "Come find our table and hear what we have planned for the fall." },
  { title: "Python Basics 4 Neuro/DataSci - Part 1", date: "2025-09-15T18:00", location: "TBA",
    blurb: "Beginner Python with Codeducation: data types, loops, functions, and plotting.",
    image: "images/python_coded.jpg" },
  { title: "Intro to ML/AI 4 NeuroSci", date: "2025-10-20T19:00", location: "WJB 2029",
    blurb: "Machine learning basics and how they show up in neuroscience. No coding experience needed.",
    image: "images/mlworkshop.jpg" },
  { title: "A Conversation with Devon White, CEO of FIELD", date: "2025-10-09T17:45", location: "Virtual",
    blurb: "A conversation with Devon White about neurotech, brain data, and where the industry is going.",
    image: "images/devonworkshop.jpg" },
  { title: "Python Basics 4 Neuro/DataSci - Part 2", date: "2025-09-18T18:00", location: "PDB A204",
    blurb: "Python with Codeducation: LFPs, spike-train plots, and summary statistics on neural data.",
    image: "images/python_coded.jpg" },
  { title: "Python Basics 4 Neuro/DataSci - Part 1", date: "2025-09-16T18:00", location: "Thagard 211",
    blurb: "Beginner Python with Codeducation: data types, loops, functions, and basic plotting.",
    image: "images/python_coded.jpg" },
  { title: "Workshop on Computational Neuroscience", date: "2025-06-27T14:00", location: "PDB A204",
    blurb: "Multi-level brain modeling with Dr. Rodrigo Pena of the FAU Stiles-Nicholson Brain Institute.",
    image: "images/PenaWorkshopWebsiteFlyer.png" },
  { title: "Intro to Python, GitHub, VS Code Workshop", date: "2025-04-17T21:15", location: "FSU",
    blurb: "Installing and using Python, GitHub, and VS Code. For complete beginners.",
    image: "images/placeholder.jpg" },
  { title: "Inaugural GBM", date: "2025-04-04T21:15", location: "FSU",
    blurb: "Our first General Body Meeting: what the club is and what's coming.",
    image: "images/gbm.png" },
];

// --- PEOPLE ---
export const LEADERSHIP = [
  { name: "Sebas Ruiz", role: "Founder + President", photo: "images/SebasRuiz.JPG",
    bio: "I work in the Sherif Lab @Brown currently working on modeling psychiatric illnesses with NeuroAI. I really enjoy underground rap and earl grey tea.",
    links: [{ label: "Website", url: "https://www.sebasruiz.site" }, { label: "LinkedIn", url: "https://www.linkedin.com/in/sebastiansebasruiz/" }] },
  { name: "Upi Shanker", role: "Vice-President + Website Coordinator", photo: "images/upi.jpg",
    bio: "I am a Freshman at FSU where I am a research assistant, data analytics intern, and front-end web developer. Outside of academics, I enjoy playing basketball and listening to music!",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/upishanker/" }] },
  { name: "Andre Quintero", role: "Project Manager", photo: "images/andre.jpg",
    bio: "I am a NeuroAI researcher involved in a few labs at FSU, focused on memory, visual and motor decoding. I intend to work with innovative teams in the MedTech industry. In my free time, I enjoy reading and I powerlift!",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/andre-quintero-312769276/" }] },
  { name: "Hafsa Baysal", role: "Treasurer", photo: "images/hafsa.png",
    bio: "I'm a second year and I never want to join the work field. I'm part of the Wilber Lab on campus and I am interested in dementia research. I enjoy quality time with friends and reading!",
    links: [] },
  { name: "Sia Kakkar", role: "Secretary", photo: "images/sia.png",
    bio: "I am a sophomore and enjoy doing neuroscience research, particularly on the cognitive effects of eating disorders. I also enjoy playing tennis and painting!",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/sia-kakkar-a4b77427b/" }] },
];

// export const GRAD_COUNCIL = [
//   { name: "Jake Tear", role: "Neuroscience PhD - Riddle Lab", photo: "images/jaketear.jpg",
//     bio: "I'm interested in improving the utility of EEG measures for precision psychiatry. Fun fact: I enjoy surfing and was on the UCSB surf team prior to joining FSU!", links: [] },
//   { name: "Yicheng Zheng", role: "Neuroscience PhD - Wilber Lab", photo: "images/yicheng.jpeg",
//     bio: "I investigate the mechanisms underlying spatial navigation using electrophysiology in rodents, and explore potential treatments for spatial awareness deficits in Alzheimer's disease. Fun fact: my dog has its own Instagram page!", links: [] },
//   { name: "Greg Owanga", role: "Biomathematics PhD - Bertram Lab", photo: "images/greg_tennessee.jpg",
//     bio: "I study how neuron populations in the gustatory cortex form and reorganize functional networks, combining network theory, signal processing and visualization. Fun fact: I'm writing a book and I'm a lifelong Lewis Hamilton fan.", links: [] },
// ];

export const MENTORS = [
  { name: "Dr. Carmen Varela", role: "Faculty Advisor", photo: "images/varela.jpg",
    bio: "Ph.D. in Computational Neuroscience @ UChicago. Assistant Professor @ FSU in Psychology and Neuroscience.",
    links: [{ label: "Lab Website", url: "https://varelalab.create.fsu.edu/" }] },
  { name: "Dr. Rodrigo Pena", role: "Pena Lab - Principal Investigator", photo: "images/rodrigo_pena.jpg",
    bio: "Ph.D. in Computational Neuroscience. Assistant Professor of Biological Sciences @ FAU (Stiles-Nicholson Brain Institute), modeling the brain across scales - ion channels, synapses, neurons, networks and systems.",
    links: [{ label: "Lab Website", url: "https://penaslab.com" }, { label: "Scholar", url: "https://scholar.google.com/citations?user=17avyRAAAAAJ" }] },
  { name: "Dr. Juan Lopez", role: "Pena Lab - Postdoctoral Researcher", photo: "images/juan_lopez.jpg",
    bio: "Ph.D. '24 and M.S. '18 @ FAU. Computational neuroscientist modeling Drosophila connectomes and neural circuits - including the Giant Fiber escape reflex - to understand how neurons communicate.",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/juanlopezphd" }] },
  { name: "Ty Roachford", role: "Pena Lab - Ph.D. Student", photo: "images/ty_roachford.jpg",
    bio: "Ph.D. student in Theoretical and Computational Neuroscience @ FAU Stiles-Nicholson Brain Institute. Interested in evolutionary, ultra-low-power intelligent networks.",
    links: [{ label: "Website", url: "https://www.tyfoodsforthought.com" }] },
];

export const TEAM = [
  { name: "Katya Sniriova", role: "Team Member", photo: "images/members/KatyaSniriova.jpeg",
    bio: "Interests: neuromorphic computing, computational biology, brain-machine interfaces. Fun fact: I've been vegetarian for 8 years!", links: [] },
  { name: "Eva Zlochower", role: "Team Member", photo: "images/members/EvaZlochower.png",
    bio: "Interests: psychopharmacology and precision treatment/diagnosis. Fun fact: I love finding new songs to learn on my guitar.", links: [] },
  { name: "Thomas Hall", role: "Team Member - Computer Science", photo: "images/members/ThomasHall.jpg",
    bio: "Interests: machine learning / NeuroAI. Fun fact: cats are my favorite animals.", links: [] },
  { name: "Victoria Montalvo", role: "Team Member - Behavioral Neuroscience & Biochemistry", photo: "images/members/VictoriaMontalvo.jpg",
    bio: "Interests: brain mapping, neuronal activity and neurodegenerative diseases. Fun fact: I love trail running and swimming!", links: [] },
];

// --- PROJECTS ---
export const APPLICATIONS = {
  open: true,
  closedNote: "Applications reopen Mid-December",
  formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScRBfy8KiEscIm7tHRrBUQkJ1IZqItF0BFHA04Gez7lOR_j0w/viewform",
};

export const CURRENT_PROJECT = null;

// Past project teams, newest first. Each card on projects.html opens a detail
// view built from the fields below. Every field is optional except name and
// summary - anything left empty or [] is simply not shown, so it is safe to
// push with sections unfinished.
//
// HOW TO FINISH THESE (the bullets below are facts only - no filler):
//   members: add one entry per person, { name, major, role } - role optional
//            e.g. { name: "Jane Doe", major: "Computer Science", role: "project lead" }
//   mission: 1-3 short bullets - why this paper/competition, what members
//            were meant to get out of it
//   outcome: 1-3 short bullets - how far it got, what you would do differently
//   gallery: add more image paths as you find photos
export const PAST_PROJECTS = [
  {
    term: "Spring 2026",
    name: "Drosophila Escape Response Replication",
    subtitle: "Pena Lab project team",
    image: "images/projects/PenaPosterGroup.jpg",
    summary: "Ported a published NEURON model of the giant-fiber escape response in Drosophila. Funded by ORCA.",
    paper: "Augustin et al. (2019), eNeuro - \"A Computational Model of the Escape Response Latency in the Giant Fiber System of Drosophila melanogaster\"",
    funding: "Open Research Community Accellerator (ORCA) - Catalytic Awards Program Grant",
    mentors: "Pena Lab, FAU Stiles-Nicholson Brain Institute",
    tools: "NEURON, Python",
    repo: "https://github.com/CompNeuroSociety-at-FSU/fork-escape-response",
    mission: [
      "Fork the published model into a shared repository so the whole team started from the same working code.",
    ],
    outcome: [
      "Three members presented a poster at the Florida Consortium of the Neurobiology of Cognition Conference.",
    ],
    members: [ { name: "Jonathan Alcineus", role: "Presenting" }, { name: "Gillian Durta", role: "Presenting" }, { name: "Devyani Jain", role: "Presenting" }, { name: "Sebas Ruiz", role: "Project Lead" }, { name: "Max Boyington", role: "Technical Lead" }, { name: "Sebastian Davalos", role: "Workshop Coordinator" },
    { name: "Mikhail Sautkin", role: "Member" }, { name: "Bianca Blevins", role: "Member" }, { name: "Cooper Wherely", role: "Member" }, { name: "Jordan Schwartz", role: "Member" }, { name: "Mrinal Raina", role: "Member" },
    { name: "Michael Murgia", role: "Member" }, { name: "Liza Kovalenko", role: "Member" }, { name: "Phuong Nguyen", role: "Member" }
     ],
    gallery: ["images/projects/PenaPosterGroup.jpg", "images/projects/pena-work-session.jpg"],
  },
  {
    term: "Fall 2025",
    name: "Retina Model Replication",
    image: "images/projects/retina-model-1.jpg",
    summary: "Replicated a published model of gap junctions and rod Ih conductance in the retina.",
    paper: "\"A Computational Study on the Role of Gap Junctions and Rod Ih Conductance in the Enhancement of the Dynamic Range of the Retina\"",
    tools: "NEURON",
    mission: [
      "Replicate the published model and try to extend it"
    ],
    outcome: [
      "Mildly successful, and a learning experience for both the members and the project leaders.",
    ],
    members: [{ name: "Andre Quintero", role: "Project Lead" }, { name: "Dion Cooper", role: "Project Associate" }, { name: "Sofia Sierra", role: "Project Member" }, { name: "Maggie Raymond", role: "Project Member" },],
    gallery: ["images/projects/retina-model-1.jpg", "images/projects/retina-model-2.jpg", "images/projects/retina-model-3.jpg"],
  },
  {
    term: "Fall 2025",
    name: "Brain-to-Text Competition Team",
    image: "images/projects/brain-to-text-1.jpg",
    summary: "Entered the 2025 Brain-to-Text Kaggle competition, decoding neural recordings into text.",
    tools: "Python, machine learning, LLMs",
    mission: [],
    outcome: [
      "Mildly successful, and a learning experience for both the members and the project leaders.",
    ],
    members: [],
    gallery: ["images/projects/brain-to-text-1.jpg", "images/projects/brain-to-text-2.jpg", "images/projects/brain-to-text-3.jpg"],
  },
];
